// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name, description, price, rating, inStock
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, description, price, rating, instock, created_at, updated_at, search_vector
`

type CreateProductParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Rating      int16          `json:"rating"`
	Instock     bool           `json:"instock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Rating,
		arg.Instock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Rating,
		&i.Instock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductDetails = `-- name: GetProductDetails :one
SELECT 
    p.id, p.name, p.description, p.price, p.rating, p.instock, p.created_at, p.updated_at,
    COALESCE(
        (
            SELECT json_agg(json_build_object('id', pc.id, 'name', pc.name, 'created_at', pc.created_at))
            FROM product_category_mapping m
            JOIN product_categories pc ON m.category_id = pc.id
            WHERE m.product_id = p.id
        ),
        '[]'
    )::json as categories,
    COALESCE(
        (
            SELECT json_agg(json_build_object('id', pi.id, 'image_url', pi.image_url, 'created_at', pi.created_at))
            FROM product_images pi
            WHERE pi.product_id = p.id
        ),
        '[]'
    )::json as product_images
FROM products p
WHERE p.id = $1
`

type GetProductDetailsRow struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Price         pgtype.Numeric     `json:"price"`
	Rating        int16              `json:"rating"`
	Instock       bool               `json:"instock"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Categories    []byte             `json:"categories"`
	ProductImages []byte             `json:"product_images"`
}

func (q *Queries) GetProductDetails(ctx context.Context, id int64) (GetProductDetailsRow, error) {
	row := q.db.QueryRow(ctx, getProductDetails, id)
	var i GetProductDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Rating,
		&i.Instock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Categories,
		&i.ProductImages,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT 
    p.id, p.name, p.description, p.price, p.rating, p.instock, p.created_at, p.updated_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', pc.id,
                'name', pc.name,
                'created_at', pc.created_at
            )
        ) FILTER (WHERE pc.id IS NOT NULL), 
        '[]'
    )::json as categories
FROM products p
LEFT JOIN product_category_mapping m ON p.id = m.product_id
LEFT JOIN product_categories pc ON m.category_id = pc.id
LEFT JOIN product_images pi ON p.id = pi.product_id
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListProductsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	Rating      int16              `json:"rating"`
	Instock     bool               `json:"instock"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Categories  []byte             `json:"categories"`
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Rating,
			&i.Instock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsFiltered = `-- name: ListProductsFiltered :many
SELECT 
    p.id, p.name, p.description, p.price, p.rating, p.instock, p.created_at, p.updated_at, COUNT(*) OVER() as total_count,
    COALESCE(
        json_agg(
            json_build_object(
                'id', pc.id,
                'name', pc.name,
                'created_at', pc.created_at
            )
        ) FILTER (WHERE pc.id IS NOT NULL), 
        '[]'
    )::json as categories,
        COALESCE(
        json_agg(
            json_build_object(
                'id', pi.id,
                'image_url', pi.image_url,
                'created_at', pi.created_at
            )
        ) FILTER (WHERE pi.id IS NOT NULL), 
        '[]'
    )::json as product_images
FROM products p
LEFT JOIN product_category_mapping m ON p.id = m.product_id
LEFT JOIN product_categories pc ON m.category_id = pc.id
LEFT JOIN product_images pi ON p.id = pi.product_id
WHERE 
    (
        $1::text = '' 
        OR (
            websearch_to_tsquery('english', $1::text) <> ''::tsquery
            AND p.search_vector @@ websearch_to_tsquery('english', $1::text)
        )
        OR p.name % $1::text  -- trigram similarity
        OR p.name ILIKE '%' || $1::text || '%'  -- partial match
    )
    AND ($2::int[] IS NULL OR cardinality($2::int[]) = 0 OR m.category_id = ANY($2))
    AND ($3::numeric IS NULL OR p.price >= $3)
    AND ($4::numeric IS NULL OR p.price <= $4)
    AND ($5::boolean IS NULL OR p.instock = $5)
GROUP BY p.id
ORDER BY
    CASE WHEN $6::text = 'relevance' AND $1::text <> '' THEN ts_rank(p.search_vector, websearch_to_tsquery('english', $1::text)) END DESC,
    CASE WHEN $6::text = 'price' AND $7::text = 'asc' THEN p.price END ASC,
    CASE WHEN $6::text = 'price' AND $7::text = 'desc' THEN p.price END DESC,
    CASE WHEN $6::text = 'rating' THEN p.rating END DESC,
    CASE WHEN $6::text = 'created_at' AND $7::text = 'asc' THEN p.created_at END ASC,
    CASE WHEN $6::text = 'created_at' AND $7::text <> 'asc' THEN p.created_at END DESC,
    p.created_at DESC
LIMIT $9::int OFFSET $8::int
`

type ListProductsFilteredParams struct {
	Q           string         `json:"q"`
	CategoryIds []int32        `json:"category_ids"`
	MinPrice    pgtype.Numeric `json:"min_price"`
	MaxPrice    pgtype.Numeric `json:"max_price"`
	InStock     pgtype.Bool    `json:"in_stock"`
	Sort        string         `json:"sort"`
	Method      string         `json:"method"`
	Offset      int32          `json:"offset"`
	Limit       int32          `json:"limit"`
}

type ListProductsFilteredRow struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Price         pgtype.Numeric     `json:"price"`
	Rating        int16              `json:"rating"`
	Instock       bool               `json:"instock"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TotalCount    int64              `json:"total_count"`
	Categories    []byte             `json:"categories"`
	ProductImages []byte             `json:"product_images"`
}

func (q *Queries) ListProductsFiltered(ctx context.Context, arg ListProductsFilteredParams) ([]ListProductsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listProductsFiltered,
		arg.Q,
		arg.CategoryIds,
		arg.MinPrice,
		arg.MaxPrice,
		arg.InStock,
		arg.Sort,
		arg.Method,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsFilteredRow
	for rows.Next() {
		var i ListProductsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Rating,
			&i.Instock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
			&i.Categories,
			&i.ProductImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
