// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_category_mapping.sql

package database

import (
	"context"
)

const createProductCategoryMapping = `-- name: CreateProductCategoryMapping :one
INSERT INTO product_category_mapping (
  product_id, category_id
) VALUES (
  $1, $2
)
RETURNING product_id, category_id, created_at, updated_at
`

type CreateProductCategoryMappingParams struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) CreateProductCategoryMapping(ctx context.Context, arg CreateProductCategoryMappingParams) (ProductCategoryMapping, error) {
	row := q.db.QueryRow(ctx, createProductCategoryMapping, arg.ProductID, arg.CategoryID)
	var i ProductCategoryMapping
	err := row.Scan(
		&i.ProductID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductCategoryMapping = `-- name: DeleteProductCategoryMapping :exec
DELETE FROM product_category_mapping
WHERE product_id = $1 AND category_id = $2
`

type DeleteProductCategoryMappingParams struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) DeleteProductCategoryMapping(ctx context.Context, arg DeleteProductCategoryMappingParams) error {
	_, err := q.db.Exec(ctx, deleteProductCategoryMapping, arg.ProductID, arg.CategoryID)
	return err
}

const getProductCategoryMapping = `-- name: GetProductCategoryMapping :one
SELECT product_id, category_id, created_at, updated_at FROM product_category_mapping
WHERE product_id = $1 AND category_id = $2 LIMIT 1
`

type GetProductCategoryMappingParams struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) GetProductCategoryMapping(ctx context.Context, arg GetProductCategoryMappingParams) (ProductCategoryMapping, error) {
	row := q.db.QueryRow(ctx, getProductCategoryMapping, arg.ProductID, arg.CategoryID)
	var i ProductCategoryMapping
	err := row.Scan(
		&i.ProductID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductCategoryMappings = `-- name: ListProductCategoryMappings :many
SELECT product_id, category_id, created_at, updated_at FROM product_category_mapping
`

func (q *Queries) ListProductCategoryMappings(ctx context.Context) ([]ProductCategoryMapping, error) {
	rows, err := q.db.Query(ctx, listProductCategoryMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategoryMapping
	for rows.Next() {
		var i ProductCategoryMapping
		if err := rows.Scan(
			&i.ProductID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
