// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_images.sql

package database

import (
	"context"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (
  product_id, image_url
) VALUES (
  $1, $2
)
RETURNING id, product_id, image_url, created_at, updated_at
`

type CreateProductImageParams struct {
	ProductID int32  `json:"product_id"`
	ImageUrl  string `json:"image_url"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage, arg.ProductID, arg.ImageUrl)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images
WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProductImage, id)
	return err
}

const getProductImage = `-- name: GetProductImage :one
SELECT id, product_id, image_url, created_at, updated_at FROM product_images
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductImage(ctx context.Context, id int64) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImage, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, image_url, created_at, updated_at FROM product_images
`

func (q *Queries) ListProductImages(ctx context.Context) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
