// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, name string) (ProductCategory, error)
	CreateProductCategoryMapping(ctx context.Context, arg CreateProductCategoryMappingParams) (ProductCategoryMapping, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithGoogle(ctx context.Context, arg CreateUserWithGoogleParams) (User, error)
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductCategory(ctx context.Context, id int64) error
	DeleteProductCategoryMapping(ctx context.Context, arg DeleteProductCategoryMappingParams) error
	DeleteProductImage(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetProductCategory(ctx context.Context, id int64) (ProductCategory, error)
	GetProductCategoryByName(ctx context.Context, name string) (ProductCategory, error)
	GetProductCategoryMapping(ctx context.Context, arg GetProductCategoryMappingParams) (ProductCategoryMapping, error)
	GetProductDetails(ctx context.Context, id int64) (GetProductDetailsRow, error)
	GetProductImage(ctx context.Context, id int64) (ProductImage, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	ListProductCategories(ctx context.Context) ([]ProductCategory, error)
	ListProductCategoryMappings(ctx context.Context) ([]ProductCategoryMapping, error)
	ListProductImages(ctx context.Context) ([]ProductImage, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
	ListProductsFiltered(ctx context.Context, arg ListProductsFilteredParams) ([]ListProductsFilteredRow, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
