-- +goose Up
ALTER TABLE users ADD COLUMN CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(), ADD COLUMN UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- +goose Down
ALTER TABLE users DROP COLUMN IF EXISTS CREATED_AT, DROP COLUMN IF EXISTS UPDATED_AT;