package repositories

import (
	sqlc "assignment-be/database/sqlc"
	"assignment-be/models"
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/jackc/pgx/v5/pgtype"
)

type postgresProductRepo struct {
	queries *sqlc.Queries
}

func NewPostgresProductRepo(q *sqlc.Queries) *postgresProductRepo {
	return &postgresProductRepo{queries: q}
}

func (r *postgresProductRepo) CreateProduct(ctx context.Context, req models.CreateProductRequest) (*models.ProductResponse, error) {
	var dbPrice pgtype.Numeric
	if err := dbPrice.Scan(fmt.Sprintf("%.2f", req.Price)); err != nil {
		return nil, fmt.Errorf("failed to scan price: %w", err)
	}

	p, err := r.queries.CreateProduct(ctx, sqlc.CreateProductParams{
		Name:        req.Name,
		Description: req.Description,
		Price:       dbPrice,
		Rating:      req.Rating,
		Instock:     req.InStock,
	})
	if err != nil {
		return nil, err
	}

	return r.mapProductRowToResponse(p.ID, p.Name, p.Description, p.Price, p.Rating, p.Instock, p.CreatedAt, nil, nil, 0), nil
}

func (r *postgresProductRepo) ListProducts(ctx context.Context) ([]models.ProductResponse, error) {
	products, err := r.queries.ListProducts(ctx)
	if err != nil {
		return nil, err
	}
	res := make([]models.ProductResponse, 0, len(products))
	for _, p := range products {
		// Use any type or the specific ListProductsRow type generated by sqlc
		res = append(res, *r.mapProductRowToResponse(p.ID, p.Name, p.Description, p.Price, p.Rating, p.Instock, p.CreatedAt, p.Categories, nil, 0))
	}
	return res, nil
}

// get product details by id
func (r *postgresProductRepo) GetProductDetails(ctx context.Context, id int64) (*models.ProductDetailsResponse, error) {
	p, err := r.queries.GetProductDetails(ctx, id)
	if err != nil {
		return nil, err
	}

	price := 0.0
	if val, err := p.Price.Value(); err == nil && val != nil {
		f, _ := strconv.ParseFloat(val.(string), 64)
		price = f
	}

	createdAt := ""
	if p.CreatedAt.Valid {
		createdAt = p.CreatedAt.Time.Format("2006-01-02 15:04:05")
	}

	var categories []models.ProductCategoryResponse
	if len(p.Categories) > 0 {
		_ = json.Unmarshal(p.Categories, &categories)
	}

	var productImages []models.ProductImageResponse
	if len(p.ProductImages) > 0 {
		_ = json.Unmarshal(p.ProductImages, &productImages)
	}

	return &models.ProductDetailsResponse{
		ID:                p.ID,
		Name:              p.Name,
		Description:       p.Description,
		Price:             price,
		Rating:            p.Rating,
		InStock:           p.Instock,
		ProductCategories: categories,
		ProductImages:     productImages,
		CreatedAt:         createdAt,
	}, nil
}

// ListProductsFiltered implements the Repository interface using the advanced SQL query.
func (r *postgresProductRepo) ListProductsFiltered(ctx context.Context, req models.ProductFilterRequest) ([]models.ProductResponse, error) {

	var minPrice, maxPrice pgtype.Numeric
	if req.MinPrice != nil {
		if err := minPrice.Scan(fmt.Sprintf("%.2f", *req.MinPrice)); err != nil {
			return nil, fmt.Errorf("invalid min_price: %w", err)
		}
	}
	if req.MaxPrice != nil {
		if err := maxPrice.Scan(fmt.Sprintf("%.2f", *req.MaxPrice)); err != nil {
			return nil, fmt.Errorf("invalid max_price: %w", err)
		}
	}

	var inStock pgtype.Bool
	if req.InStock != nil {
		inStock = pgtype.Bool{Bool: *req.InStock, Valid: true}
	}

	var categoryIDs []int32
	if len(req.CategoryIDs) > 0 {
		categoryIDs = req.CategoryIDs
	}

	products, err := r.queries.ListProductsFiltered(ctx, sqlc.ListProductsFilteredParams{
		Q:           req.Q,
		CategoryIds: categoryIDs,
		MinPrice:    minPrice,
		MaxPrice:    maxPrice,
		InStock:     inStock,
		Sort:        req.Sort,
		Method:      req.Method,
		Offset:      req.Offset,
		Limit:       req.Limit,
	})
	if err != nil {
		return nil, err
	}

	res := make([]models.ProductResponse, 0, len(products))
	for _, p := range products {
		res = append(res, *r.mapProductRowToResponse(p.ID, p.Name, p.Description, p.Price, p.Rating, p.Instock, p.CreatedAt, p.Categories, p.ProductImages, p.TotalCount))
	}
	return res, nil
}

// mapProductRowToResponse is a private helper to convert DB result rows to API response models.
func (r *postgresProductRepo) mapProductRowToResponse(
	id int64, name, description string,
	dbPrice pgtype.Numeric, rating int16,
	instock bool, createdAtTz pgtype.Timestamptz,
	categoriesJSON []byte,
	productImagesJSON []byte,
	totalCount int64,
) *models.ProductResponse {
	var price float64
	if val, err := dbPrice.Value(); err == nil && val != nil {
		f, _ := strconv.ParseFloat(val.(string), 64)
		price = f
	}

	createdAt := ""
	if createdAtTz.Valid {
		createdAt = createdAtTz.Time.Format("2006-01-02 15:04:05")
	}

	var categories []models.ProductCategoryResponse
	if len(categoriesJSON) > 0 {
		_ = json.Unmarshal(categoriesJSON, &categories)
	}

	var productImages []models.ProductImageResponse
	if len(productImagesJSON) > 0 {
		_ = json.Unmarshal(productImagesJSON, &productImages)
	}

	return &models.ProductResponse{
		ID:                id,
		Name:              name,
		Description:       description,
		Price:             price,
		Rating:            rating,
		InStock:           instock,
		ProductCategories: categories,
		ProductImages:     productImages,
		CreatedAt:         createdAt,
		TotalCount:        totalCount,
	}
}
